#page title
page_title                                : Persistent                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1577234546                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : de                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Stay persistent with your goals.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                
your_link                                 :                     
your_city                                 :                                 
email_address                             : persistentapp@protonmail.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : devSkilluminati
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Build healthy habits
    description                           : The progress-circle will make you want to complete your habits every day, so you can build long lasting habits.
    fontawesome_icon_name                 : check-circle
    
  - title                                 : See your progress
    description                           : Through a lovely graph view you can see how you did in the past, so you can stay motivated!
    fontawesome_icon_name                 : bar-chart

  - title                                 : Complete afterwards or in advance
    description                           : You can complete habits for days in the past or the future. Who doesn´t like having a choice?
    fontawesome_icon_name                 : calendar

  - title                                 : Notifications
    description                           : Get reminded of your habit and write a custom message to keep you mativated.
    fontawesome_icon_name                 : bell

  - title                                 : Native
    description                           : If you know iOS, you will know how to use the app. It just feels right. And it looks good.
    fontawesome_icon_name                 : home
  
  - title                                 : More coming soon
    description                           : I´m already planning some things. Currently, my eyes are on shortcuts support and an WatchOS app.
    fontawesome_icon_name                 : info



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
